apiVersion: apps/v1
kind: Deployment
metadata: 
  name: naveen-webapp
spec:
  selector:
    matchLabels:
      name: my-webapp
  template:
    metadata:
      labels:
        name: my-webapp
    spec:
      containers:
        - name: webapp
          image: 10.0.1.157:5000/my-webapp
  replicas: 1
