apiVersion: apps/v1
kind: Deployment
metadata: 
  name: naveen-webapp
spec:
  selector:
    matchLabels:
      name: my-web
  template:
    metadata:
      labels:
        name: my-web
    spec:
      containers:
        - name: my-web
          image: naveenkumar003/my-web:v1
  replicas: 1
