apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.labels.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.labels.name }}
    spec:
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.image.repository }}
